//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TheBigDukan
{
    using System;
    using System.Collections.Generic;
    
    public partial class Reg_Table
    {
        public int id { get; set; }
        public string name { get; set; }
        public string email { get; set; }
        public string address { get; set; }
        public string cellNo { get; set; }
        public string password { get; set; }
        public string userType { get; set; }
        public System.TimeSpan time { get; set; }
        public string date { get; set; }
        public byte[] photo { get; set; }
        public bool isActive { get; set; }
    }
}
