//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TheBigDukan
{
    using System;
    using System.Collections.Generic;
    
    public partial class TestingTable
    {
        public string name { get; set; }
        public int ager { get; set; }
        public string last_name { get; set; }
        public int F_name { get; set; }
        public int id { get; set; }
    }
}
